replicaCount: 2

image:
  repository: alexashley/demo-app
  pullPolicy: IfNotPresent
  tag: 77f21d0

probe:
  path: /healthz

nameOverride: "demo-app"
fullnameOverride: "demo-app"

service:
  type: ClusterIP
  port: 1234

ingress:
  enabled: true
  hostname: demo-app.ahalab.dev
  path: "/"

resources:
  requests:
    memory: 100Mi
    cpu: 200m
  limits:
    memory: 500Mi
    cpu: 400m

ingress-nginx:
  controller:
    admissionWebhooks:
      enabled: false
    replicaCount: 3
    resources:
      requests:
        memory: 50Mi
        cpu: 200m
      limits:
        memory: 100Mi
        cpu: 400m
  defaultBackend:
    enabled: true
    replicaCount: 3
    resources:
      requests:
        memory: 50Mi
        cpu: 200m
      limits:
        memory: 100Mi
        cpu: 400m