replicaCount: 3

image:
  repository: alexashley/demo-app
  pullPolicy: IfNotPresent
  tag: 88c7a28

probe:
  path: /healthz

nameOverride: "demo-app"
fullnameOverride: "demo-app"

service:
  type: ClusterIP
  port: 1234

ingress:
  enabled: true
  hosts:
    - host: demo-app.ahalab.dev
      paths:
        - "/"
  tls: []

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi


