region                 = "us-central1"
project_id             = "aha-demo-app"
node_pool_machine_type = "e2-standard-2"
node_pool_version      = "1.15.12-gke.9"
cluster_version        = "1.15.12-gke.9"
