apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "demo-app.fullname" . }}
  namespace: {{ include "demo-app.fullname" . }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "demo-app.selectorLabels" . | nindent 6 }}
